steps:
  - label: ":calendar: Calculate version"
    command: .buildkite/steps/set-calver

  - wait

  - label: ":clojars: Deploy to Clojars"
    secrets:
      - CLOJARS_USERNAME
      - CLOJARS_PASSWORD
    command: .buildkite/steps/deploy-clojars

  - wait

  - label: ":github: Create GitHub release"
    secrets:
      - GITHUB_TOKEN
    command: .buildkite/steps/create-github-release
