steps:
  - label: ":clojure: Test"
    command: .buildkite/steps/test

  - block: ":rocket: Release"
    if: build.branch == "main"
    prompt: "Create a new release?"

  - label: ":pipeline: Upload release pipeline"
    if: build.branch == "main"
    command: buildkite-agent pipeline upload .buildkite/pipeline.release.yml
