#!/usr/bin/env bash
set -euo pipefail

echo "--- :gear: Installing mise"
curl https://mise.run | sh
export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
mise install

echo "--- :clojure: Running tests"
clojure -M:test
